### ISSUE TITLE
idk where else to put it soo i complain here

### ISSUE THREAD

**Issue by Renokas1** [HalbFettKaese/common-shaders#2]
fix the anime speed lines resource pack pls, it does not work consistently + seems to only start working when looking up aka when i want to use it for boat racing it just does not work at all

**Comment by HalbFettKaese** [comment]
Hi, I know this is a bit late (I didn't feel like messing with the anime zoom pack for a while) but I just made a patch that fixes this + some other things, in case you still want to check it out
